let shopItemsData = [{
    id:"fsiufhs",
    name:"Casual shirt",
    price:45,
    desc:"Lorem ipsum dolor sit amet consectetur adipisicing.",
    img:"images/img-1.jpg",},{id:"vbvbxmv",
    name:"Office shirt",
    price:100,
    desc:"Lorem ipsum dolor sit amet consectetur adipisicing.",
    img:"images/img-2.jpg"},{id:"djkgajdhakj",
    name:"T shirt",
    price:25,
    desc:"Lorem ipsum dolor sit amet consectetur adipisicing.",
    img:"images/img-3.jpg"},{id:"wwwwwwe",
    name:"Mens suit",
    price:300,
    desc:"Lorem ipsum dolor sit amet consectetur adipisicing.",
    img:"images/img-4.jpg"}];
